version: 2

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:9.6.16-alpine
        environment:
          NODE_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_DB: name_of_your_db_test
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Compile
          command: yarn build-ts
      - run:
          name: Migrate
          command: yarn migrate:up:test
      - run:
          name: tests
          command: yarn test
